export const Users = [
    {
      id:1,
      profilePicture: "/images/person/1.jpg",
      username: "harsh Rawal",
    },
    {
      id:2,
      profilePicture: "/images/person/2.jpg",
      username: "Jenny louis",
    },
    {
      id:3,
      profilePicture: "/images/person/3.jpg",
      username: "Akhil dami",
    },
    {
      id:4,
      profilePicture: "/images/person/4.jpg",
      username: "Abhisek mittal",
    },
    {
      id:5,
      profilePicture: "/images/person/5.jpg",
      username: "Shriya kukreti",
    },
    {
      id:6,
      profilePicture: "/images/person/6.jpg",
      username: "maya raj",
    },
    {
      id:7,
      profilePicture: "/images/person/10.jpg",
      username: "Amit singh",
    },
    {
      id:8,
      profilePicture: "/images/person/11.jpg",
      username: "Kaushik kartk",
    },
 
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc: "Love is around us",
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc: "hate urself first and You will hate the world",
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc: "like if u like",
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc: "keep showring ur Love",
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc: "Nothing will last forever",
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "Be Happy",
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  